// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssetID is the content address (sha256, hex) of an Asset, so re-running a
 * task that produces identical output is a no-op.
 */
export type AssetID = string;

/**
 * ChapterDelta is the subset of a Chapter that changes often enough to stream.
 */
export interface ChapterDelta {
    "id": ChapterID;
    "videoId": VideoID;
    "ordinal": number;
    "title": string;
    "hasScript": boolean;
    "audioAssetId"?: AssetID | null;

    /**
     * Travels with AudioAssetID because it is a fact about that same file. The
     * script body is deliberately off the wire and fetched on notice, but a
     * float is not worth a round trip — and without it a chapter would show its
     * narration arriving while its length stayed at zero.
     */
    "audioDurationSeconds"?: number;
    "slideAssetIds"?: AssetID[] | null;
    "clipAssetId"?: AssetID | null;
    "updatedAt": string;
}

/**
 * ChapterID is the opaque identifier of a Chapter.
 */
export type ChapterID = string;

/**
 * Event is one message on the multiplexed SSE stream: one stream per client
 * carries every video.
 */
export interface Event {
    /**
     * ID increases monotonically; a reconnecting client sends it back as
     * Last-Event-ID to resume without a full reload.
     */
    "id": number;
    "kind": EventKind;
    "videoId"?: VideoID;
    "at": string;
    "tasks"?: TaskDelta[] | null;
    "video"?: VideoDelta | null;
    "chapters"?: ChapterDelta[] | null;
    "scheduler"?: SchedulerDelta | null;
}

/**
 * EventKind names a delta pushed to clients over SSE. Events carry the delta,
 * never a full state dump.
 */
export enum EventKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of event kinds.
     *
     * EventKindBatch carries every delta accumulated for one video within a
     * coalescing window, so a 50-chapter render is not hundreds of messages.
     */
    EventKindBatch = "batch",

    /**
     * EventKindScheduler carries pool utilisation for the operator console.
     */
    EventKindScheduler = "scheduler",
};

/**
 * GateKind names a human approval gate.
 */
export enum GateKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of gates. GateNone means the task releases its dependents
     * itself.
     */
    GateNone = "",
    GateBlueprint = "blueprint",

    /**
     * GateScript rides on every chapter's script at once, so unlike the other
     * two it is a set of parked tasks rather than one. It needs no barrier node:
     * the scripts are siblings under the blueprint and run to completion on
     * their own, and each holds only its own chapter's narration, so the whole
     * stage settles and nothing downstream of it starts.
     */
    GateScript = "script",
    GateUpload = "upload",
};

/**
 * Pool is a global concurrency pool: video A's chapter 3 competes with video
 * B's chapter 40 for the same slots.
 */
export enum Pool {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of pools. A task acquires exactly one slot in exactly one
     * pool and holds it for the duration of the provider call.
     *
     * PoolLLM covers blueprint, script, slide-prompt priming and metadata.
     */
    PoolLLM = "llm",

    /**
     * PoolTTS covers narration synthesis.
     */
    PoolTTS = "tts",

    /**
     * PoolImage covers slide generation — the longest pole in the pipeline.
     */
    PoolImage = "image",

    /**
     * PoolCompose covers per-chapter clips and the final concat.
     */
    PoolCompose = "compose",

    /**
     * PoolCache covers the per-chapter slide-prompt reads against the coalesced
     * batch, which must not occupy a real LLM slot.
     */
    PoolCache = "cache",

    /**
     * PoolUpload covers the YouTube upload.
     */
    PoolUpload = "upload",
};

/**
 * PoolStat is the live utilisation of one pool, for the operator console.
 */
export interface PoolStat {
    "pool": Pool;
    "limit": number;
    "inFlight": number;
    "queued": number;
}

/**
 * SchedulerDelta is the whole pool table plus aggregate counters.
 */
export interface SchedulerDelta {
    "pools": PoolStat[] | null;
    "ready": number;
    "running": number;
    "blocked": number;
    "videos": number;
    "uptimeSeconds": number;
    "updatedAt": string;
}

/**
 * TaskDelta is the subset of a Task that changes often enough to stream.
 */
export interface TaskDelta {
    "id": TaskID;
    "videoId": VideoID;
    "chapterId"?: ChapterID | null;
    "kind": TaskKind;
    "ordinal": number;
    "index": number;
    "state": TaskState;
    "pool": Pool;
    "gate"?: GateKind;
    "attempt": number;

    /**
     * Percent is how far a long-running task has got, 0-100. It is meaningful
     * only while State is running, and it is never persisted: no delta built
     * from a stored Task carries one. It exists so a concat that takes three
     * minutes can say so without a state change to hang the report on.
     */
    "percent"?: number;

    /**
     * Stale rides along so the UI can flag a task without refetching the video.
     */
    "stale": boolean;
    "error"?: string;

    /**
     * NotBefore rides along because a retryable failure falls back to blocked,
     * and nothing else distinguishes a dependency wait from a backoff timer.
     */
    "notBefore"?: string | null;
    "updatedAt": string;
}

/**
 * TaskID is derived from the video, kind, ordinal and index rather than
 * generated, so enqueueing the same DAG twice is an idempotent upsert.
 */
export type TaskID = string;

/**
 * TaskKind identifies a node type in the per-video DAG.
 */
export enum TaskKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of task kinds.
     *
     * TaskKindBlueprint produces the chapter outline for the whole video.
     */
    TaskKindBlueprint = "blueprint",

    /**
     * TaskKindPrimeSlidePrompts occupies a real LLM slot and produces every
     * chapter's slide prompts in one call, so there is a batch to coalesce.
     */
    TaskKindPrimeSlidePrompts = "prime_slide_prompts",

    /**
     * TaskKindSlidePrompts is the per-chapter cache read against that batch.
     */
    TaskKindSlidePrompts = "slide_prompts",

    /**
     * TaskKindScript writes one chapter's narration.
     */
    TaskKindScript = "script",

    /**
     * TaskKindTTS narrates one chapter.
     */
    TaskKindTTS = "tts",

    /**
     * TaskKindSlide generates one slide for one chapter.
     */
    TaskKindSlide = "slide",

    /**
     * TaskKindClip composes one chapter's audio and slides into a clip.
     */
    TaskKindClip = "clip",

    /**
     * TaskKindConcat joins every clip into the final render.
     */
    TaskKindConcat = "concat",

    /**
     * TaskKindMetadata writes the YouTube title, description and tags.
     */
    TaskKindMetadata = "metadata",

    /**
     * TaskKindThumbnailPlan writes one caption and one icon prompt per cell.
     */
    TaskKindThumbnailPlan = "thumbnail_plan",

    /**
     * TaskKindThumbnailIcon generates one cell's icon.
     */
    TaskKindThumbnailIcon = "thumbnail_icon",

    /**
     * TaskKindThumbnail composes the icons under the metadata task's hook.
     */
    TaskKindThumbnail = "thumbnail",

    /**
     * TaskKindUpload publishes the final render.
     */
    TaskKindUpload = "upload",
};

/**
 * TaskState is the durable state of a single task.
 */
export enum TaskState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of task states.
     *
     * TaskStateBlocked has unmet dependencies and is not in the ready set.
     */
    TaskStateBlocked = "blocked",

    /**
     * TaskStateReady is runnable and waiting for a pool slot.
     */
    TaskStateReady = "ready",

    /**
     * TaskStateRunning holds a pool slot and is inside a provider call.
     */
    TaskStateRunning = "running",

    /**
     * TaskStateAwaitingApproval succeeded but sits on a gate, holding its
     * dependents and consuming nothing.
     */
    TaskStateAwaitingApproval = "awaiting_approval",

    /**
     * TaskStateSucceeded completed and released its dependents.
     */
    TaskStateSucceeded = "succeeded",

    /**
     * TaskStateFailed exhausted its retries.
     */
    TaskStateFailed = "failed",

    /**
     * TaskStateCancelled was stopped with its video.
     */
    TaskStateCancelled = "cancelled",
};

/**
 * VideoDelta is the subset of a Video that changes often enough to stream. It
 * carries the id alone: the scheduler never loads a video row, so a ref here
 * would always go out empty and a client keyed off it would drop every update.
 */
export interface VideoDelta {
    "id": VideoID;
    "state": VideoState;

    /**
     * Done and Total drive the progress bar without a refetch.
     */
    "done": number;
    "total": number;
    "failed": number;
    "running": number;
    "error"?: string;
    "updatedAt": string;
}

/**
 * VideoID is the opaque identifier of a Video.
 */
export type VideoID = string;

/**
 * VideoState is the lifecycle state of a Video.
 */
export enum VideoState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The complete set of video lifecycle states.
     *
     * VideoStateDraft is a video that exists but whose DAG has not been enqueued.
     */
    VideoStateDraft = "draft",

    /**
     * VideoStateRunning has at least one task in flight or ready.
     */
    VideoStateRunning = "running",

    /**
     * VideoStateAwaitingApproval is parked on a gate and consumes no resources.
     */
    VideoStateAwaitingApproval = "awaiting_approval",

    /**
     * VideoStateBlocked has no runnable task and at least one permanently failed
     * one.
     */
    VideoStateBlocked = "blocked",

    /**
     * VideoStateCompleted finished the whole DAG, upload included.
     */
    VideoStateCompleted = "completed",

    /**
     * VideoStateFailed exhausted retries on a task with no path forward.
     */
    VideoStateFailed = "failed",

    /**
     * VideoStateCancelled was stopped by the operator.
     */
    VideoStateCancelled = "cancelled",
};
