import type { components } from './schema'
import type {
  Asset,
  Channel,
  Chapter,
  Metadata,
  PoolStat,
  SchedulerStatus,
  Setting,
  Style,
  Task,
  TaskCounts,
  UploadRecord,
  Video,
} from './types'

/**
 * The client's types are checked against the server's OpenAPI document.
 *
 * `schema.d.ts` is generated by `npm run gen:api` from the spec huma emits from
 * the Go structs, so a field that changes shape in Go stops compiling here.
 *
 * The assertions run one way on purpose: the server's types must be assignable
 * to the hand-written ones, which may be narrower (literal unions where the
 * server declares a plain string).
 */
type Schemas = components['schemas']

/** Fails to compile unless Server is assignable to Client. */
type Matches<Server extends Client, Client> = Server extends Client ? true : never

// Anything the schema marks optional arrives as `| undefined`; the client types
// use optional properties for exactly those fields.
type Assertions = [
  Matches<Schemas['StyleDTO'], Style>,
  Matches<Schemas['ChannelDTO'], Channel>,
  Matches<Schemas['TaskCountsDTO'], TaskCounts>,
  Matches<Schemas['MetadataDTO'], Metadata>,
  Matches<Schemas['UploadDTO'], UploadRecord>,
  Matches<Schemas['VideoDTO'], Video>,
  Matches<Schemas['ChapterDTO'], Chapter>,
  Matches<Schemas['TaskDTO'], Task>,
  Matches<Schemas['PoolStatDTO'], PoolStat>,
  Matches<Schemas['SchedulerStatusDTO'], SchedulerStatus>,
  Matches<Schemas['SettingDTO'], Setting>,
  Matches<Schemas['AssetDTO'], Asset>,
]

// Referencing the tuple keeps it from being erased as unused.
export type ApiContractIsUpToDate = Assertions
