// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package sqlcgen

import (
	"context"
)

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, video_id, chapter_id, kind, path, size, mime, provenance, created_at FROM assets WHERE id = ?
`

func (q *Queries) GetAssetByID(ctx context.Context, id string) (Asset, error) {
	row := q.queryRow(ctx, q.getAssetByIDStmt, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChapterID,
		&i.Kind,
		&i.Path,
		&i.Size,
		&i.Mime,
		&i.Provenance,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByVideo = `-- name: ListAssetsByVideo :many
SELECT id, video_id, chapter_id, kind, path, size, mime, provenance, created_at FROM assets WHERE video_id = ? ORDER BY created_at
`

func (q *Queries) ListAssetsByVideo(ctx context.Context, videoID string) ([]Asset, error) {
	rows, err := q.query(ctx, q.listAssetsByVideoStmt, listAssetsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChapterID,
			&i.Kind,
			&i.Path,
			&i.Size,
			&i.Mime,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putAsset = `-- name: PutAsset :exec
INSERT INTO assets (id, video_id, chapter_id, kind, path, size, mime, provenance, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type PutAssetParams struct {
	ID         string
	VideoID    string
	ChapterID  *string
	Kind       string
	Path       string
	Size       int64
	Mime       string
	Provenance string
	CreatedAt  int64
}

// Content-addressed: an identical byte stream re-uses the existing row, which
// is what makes a partial re-run cheap (goal.md section 3).
func (q *Queries) PutAsset(ctx context.Context, arg PutAssetParams) error {
	_, err := q.exec(ctx, q.putAssetStmt, putAsset,
		arg.ID,
		arg.VideoID,
		arg.ChapterID,
		arg.Kind,
		arg.Path,
		arg.Size,
		arg.Mime,
		arg.Provenance,
		arg.CreatedAt,
	)
	return err
}
