// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (
    id, slug, name, description, tone, voice, image_style, language,
    words_per_chapter, credentials, video_seq, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChannelParams struct {
	ID              string
	Slug            string
	Name            string
	Description     string
	Tone            string
	Voice           string
	ImageStyle      string
	Language        string
	WordsPerChapter int64
	Credentials     string
	VideoSeq        int64
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.exec(ctx, q.createChannelStmt, createChannel,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Tone,
		arg.Voice,
		arg.ImageStyle,
		arg.Language,
		arg.WordsPerChapter,
		arg.Credentials,
		arg.VideoSeq,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteChannelStmt, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, slug, name, description, tone, voice, image_style, language, words_per_chapter, credentials, video_seq, created_at, updated_at FROM channels WHERE id = ?
`

func (q *Queries) GetChannelByID(ctx context.Context, id string) (Channel, error) {
	row := q.queryRow(ctx, q.getChannelByIDStmt, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Tone,
		&i.Voice,
		&i.ImageStyle,
		&i.Language,
		&i.WordsPerChapter,
		&i.Credentials,
		&i.VideoSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, slug, name, description, tone, voice, image_style, language, words_per_chapter, credentials, video_seq, created_at, updated_at FROM channels WHERE slug = ?
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.queryRow(ctx, q.getChannelBySlugStmt, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Tone,
		&i.Voice,
		&i.ImageStyle,
		&i.Language,
		&i.WordsPerChapter,
		&i.Credentials,
		&i.VideoSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, slug, name, description, tone, voice, image_style, language, words_per_chapter, credentials, video_seq, created_at, updated_at FROM channels ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.query(ctx, q.listChannelsStmt, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Tone,
			&i.Voice,
			&i.ImageStyle,
			&i.Language,
			&i.WordsPerChapter,
			&i.Credentials,
			&i.VideoSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET name = ?, description = ?, tone = ?, voice = ?, image_style = ?,
    language = ?, words_per_chapter = ?, credentials = ?, updated_at = ?
WHERE id = ?
`

type UpdateChannelParams struct {
	Name            string
	Description     string
	Tone            string
	Voice           string
	ImageStyle      string
	Language        string
	WordsPerChapter int64
	Credentials     string
	UpdatedAt       int64
	ID              string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.exec(ctx, q.updateChannelStmt, updateChannel,
		arg.Name,
		arg.Description,
		arg.Tone,
		arg.Voice,
		arg.ImageStyle,
		arg.Language,
		arg.WordsPerChapter,
		arg.Credentials,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertChannelBySlug = `-- name: UpsertChannelBySlug :exec
INSERT INTO channels (
    id, slug, name, description, tone, voice, image_style, language,
    words_per_chapter, credentials, video_seq, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (slug) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    tone = excluded.tone,
    voice = excluded.voice,
    image_style = excluded.image_style,
    language = excluded.language,
    words_per_chapter = excluded.words_per_chapter,
    updated_at = excluded.updated_at
`

type UpsertChannelBySlugParams struct {
	ID              string
	Slug            string
	Name            string
	Description     string
	Tone            string
	Voice           string
	ImageStyle      string
	Language        string
	WordsPerChapter int64
	Credentials     string
	VideoSeq        int64
	CreatedAt       int64
	UpdatedAt       int64
}

// Seeds are upserts by natural key, so running the seed a second time updates
// in place instead of creating a duplicate.
func (q *Queries) UpsertChannelBySlug(ctx context.Context, arg UpsertChannelBySlugParams) error {
	_, err := q.exec(ctx, q.upsertChannelBySlugStmt, upsertChannelBySlug,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Tone,
		arg.Voice,
		arg.ImageStyle,
		arg.Language,
		arg.WordsPerChapter,
		arg.Credentials,
		arg.VideoSeq,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
