// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_seq.sql

package sqlcgen

import (
	"context"
)

const getVideoSeq = `-- name: GetVideoSeq :one
SELECT video_seq FROM channels WHERE id = ?
`

func (q *Queries) GetVideoSeq(ctx context.Context, id string) (int64, error) {
	row := q.queryRow(ctx, q.getVideoSeqStmt, getVideoSeq, id)
	var video_seq int64
	err := row.Scan(&video_seq)
	return video_seq, err
}

const incrementVideoSeq = `-- name: IncrementVideoSeq :exec

UPDATE channels SET video_seq = video_seq + 1, updated_at = ? WHERE id = ?
`

type IncrementVideoSeqParams struct {
	UpdatedAt int64
	ID        string
}

// Video refs are minted from a per-channel counter. The increment and the read
// back run inside one write transaction on the single writer connection, so
// nothing can interleave between them.
func (q *Queries) IncrementVideoSeq(ctx context.Context, arg IncrementVideoSeqParams) error {
	_, err := q.exec(ctx, q.incrementVideoSeqStmt, incrementVideoSeq, arg.UpdatedAt, arg.ID)
	return err
}
