// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package sqlcgen

import (
	"context"
)

const deleteChaptersByVideo = `-- name: DeleteChaptersByVideo :exec
DELETE FROM chapters WHERE video_id = ?
`

func (q *Queries) DeleteChaptersByVideo(ctx context.Context, videoID string) error {
	_, err := q.exec(ctx, q.deleteChaptersByVideoStmt, deleteChaptersByVideo, videoID)
	return err
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, video_id, ordinal, title, summary, script, slide_prompts_json, audio_asset_id, slide_asset_ids_json, clip_asset_id, duration_seconds, created_at, updated_at, estimated_words FROM chapters WHERE id = ?
`

func (q *Queries) GetChapterByID(ctx context.Context, id string) (Chapter, error) {
	row := q.queryRow(ctx, q.getChapterByIDStmt, getChapterByID, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Ordinal,
		&i.Title,
		&i.Summary,
		&i.Script,
		&i.SlidePromptsJson,
		&i.AudioAssetID,
		&i.SlideAssetIdsJson,
		&i.ClipAssetID,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimatedWords,
	)
	return i, err
}

const listChaptersByVideo = `-- name: ListChaptersByVideo :many
SELECT id, video_id, ordinal, title, summary, script, slide_prompts_json, audio_asset_id, slide_asset_ids_json, clip_asset_id, duration_seconds, created_at, updated_at, estimated_words FROM chapters WHERE video_id = ? ORDER BY ordinal
`

func (q *Queries) ListChaptersByVideo(ctx context.Context, videoID string) ([]Chapter, error) {
	rows, err := q.query(ctx, q.listChaptersByVideoStmt, listChaptersByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Ordinal,
			&i.Title,
			&i.Summary,
			&i.Script,
			&i.SlidePromptsJson,
			&i.AudioAssetID,
			&i.SlideAssetIdsJson,
			&i.ClipAssetID,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EstimatedWords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChapterAudio = `-- name: SetChapterAudio :exec
UPDATE chapters SET audio_asset_id = ?, updated_at = ? WHERE id = ?
`

type SetChapterAudioParams struct {
	AudioAssetID *string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) SetChapterAudio(ctx context.Context, arg SetChapterAudioParams) error {
	_, err := q.exec(ctx, q.setChapterAudioStmt, setChapterAudio, arg.AudioAssetID, arg.UpdatedAt, arg.ID)
	return err
}

const setChapterClip = `-- name: SetChapterClip :exec
UPDATE chapters SET clip_asset_id = ?, updated_at = ? WHERE id = ?
`

type SetChapterClipParams struct {
	ClipAssetID *string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) SetChapterClip(ctx context.Context, arg SetChapterClipParams) error {
	_, err := q.exec(ctx, q.setChapterClipStmt, setChapterClip, arg.ClipAssetID, arg.UpdatedAt, arg.ID)
	return err
}

const setChapterPlan = `-- name: SetChapterPlan :exec
UPDATE chapters
SET title = ?, summary = ?, estimated_words = ?, updated_at = ?
WHERE id = ?
`

type SetChapterPlanParams struct {
	Title          string
	Summary        string
	EstimatedWords int64
	UpdatedAt      int64
	ID             string
}

// The three fields the blueprint plans with, written together because they are
// edited together: re-budgeting a chapter's words usually means rewriting the
// summary that earned them. Everything a task produced is left alone -- this
// statement touches the plan and nothing derived from it.
func (q *Queries) SetChapterPlan(ctx context.Context, arg SetChapterPlanParams) error {
	_, err := q.exec(ctx, q.setChapterPlanStmt, setChapterPlan,
		arg.Title,
		arg.Summary,
		arg.EstimatedWords,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setChapterPrompt = `-- name: SetChapterPrompt :exec
UPDATE chapters
SET slide_prompts_json = json_set(slide_prompts_json, CAST(?1 AS TEXT), CAST(?2 AS TEXT)),
    updated_at = ?3
WHERE id = ?4
`

type SetChapterPromptParams struct {
	Path      string
	Prompt    string
	UpdatedAt int64
	ID        string
}

// Written by index for the same reason SetChapterSlide is: the operator is
// replacing one prompt, and rewriting the whole array would carry back whatever
// the row held when it was read.
func (q *Queries) SetChapterPrompt(ctx context.Context, arg SetChapterPromptParams) error {
	_, err := q.exec(ctx, q.setChapterPromptStmt, setChapterPrompt,
		arg.Path,
		arg.Prompt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setChapterPrompts = `-- name: SetChapterPrompts :exec
UPDATE chapters SET slide_prompts_json = ?, updated_at = ? WHERE id = ?
`

type SetChapterPromptsParams struct {
	SlidePromptsJson string
	UpdatedAt        int64
	ID               string
}

func (q *Queries) SetChapterPrompts(ctx context.Context, arg SetChapterPromptsParams) error {
	_, err := q.exec(ctx, q.setChapterPromptsStmt, setChapterPrompts, arg.SlidePromptsJson, arg.UpdatedAt, arg.ID)
	return err
}

const setChapterScript = `-- name: SetChapterScript :exec
UPDATE chapters SET script = ?, duration_seconds = ?, updated_at = ? WHERE id = ?
`

type SetChapterScriptParams struct {
	Script          string
	DurationSeconds float64
	UpdatedAt       int64
	ID              string
}

// Field-scoped updates. Two slide tasks for the same chapter run concurrently,
// so a read-modify-write of the whole row would lose one of them; each of these
// is a single atomic statement instead.
func (q *Queries) SetChapterScript(ctx context.Context, arg SetChapterScriptParams) error {
	_, err := q.exec(ctx, q.setChapterScriptStmt, setChapterScript,
		arg.Script,
		arg.DurationSeconds,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setChapterSlide = `-- name: SetChapterSlide :exec
UPDATE chapters
SET slide_asset_ids_json = json_set(slide_asset_ids_json, CAST(?1 AS TEXT), CAST(?2 AS TEXT)),
    updated_at = ?3
WHERE id = ?4
`

type SetChapterSlideParams struct {
	Path      string
	AssetID   string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetChapterSlide(ctx context.Context, arg SetChapterSlideParams) error {
	_, err := q.exec(ctx, q.setChapterSlideStmt, setChapterSlide,
		arg.Path,
		arg.AssetID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertChapter = `-- name: UpsertChapter :exec
INSERT INTO chapters (
    id, video_id, ordinal, title, summary, script, slide_prompts_json,
    audio_asset_id, slide_asset_ids_json, clip_asset_id, duration_seconds,
    estimated_words, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    ordinal = excluded.ordinal,
    title = excluded.title,
    summary = excluded.summary,
    script = excluded.script,
    slide_prompts_json = excluded.slide_prompts_json,
    audio_asset_id = excluded.audio_asset_id,
    slide_asset_ids_json = excluded.slide_asset_ids_json,
    clip_asset_id = excluded.clip_asset_id,
    duration_seconds = excluded.duration_seconds,
    estimated_words = excluded.estimated_words,
    updated_at = excluded.updated_at
`

type UpsertChapterParams struct {
	ID                string
	VideoID           string
	Ordinal           int64
	Title             string
	Summary           string
	Script            string
	SlidePromptsJson  string
	AudioAssetID      *string
	SlideAssetIdsJson string
	ClipAssetID       *string
	DurationSeconds   float64
	EstimatedWords    int64
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.exec(ctx, q.upsertChapterStmt, upsertChapter,
		arg.ID,
		arg.VideoID,
		arg.Ordinal,
		arg.Title,
		arg.Summary,
		arg.Script,
		arg.SlidePromptsJson,
		arg.AudioAssetID,
		arg.SlideAssetIdsJson,
		arg.ClipAssetID,
		arg.DurationSeconds,
		arg.EstimatedWords,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
