// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.applyTaskTransitionStmt, err = db.PrepareContext(ctx, applyTaskTransition); err != nil {
		return nil, fmt.Errorf("error preparing query ApplyTaskTransition: %w", err)
	}
	if q.countAssetOwnersStmt, err = db.PrepareContext(ctx, countAssetOwners); err != nil {
		return nil, fmt.Errorf("error preparing query CountAssetOwners: %w", err)
	}
	if q.countTasksByVideoStmt, err = db.PrepareContext(ctx, countTasksByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query CountTasksByVideo: %w", err)
	}
	if q.countVideosStmt, err = db.PrepareContext(ctx, countVideos); err != nil {
		return nil, fmt.Errorf("error preparing query CountVideos: %w", err)
	}
	if q.createChannelStmt, err = db.PrepareContext(ctx, createChannel); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChannel: %w", err)
	}
	if q.createVideoStmt, err = db.PrepareContext(ctx, createVideo); err != nil {
		return nil, fmt.Errorf("error preparing query CreateVideo: %w", err)
	}
	if q.deleteChannelStmt, err = db.PrepareContext(ctx, deleteChannel); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChannel: %w", err)
	}
	if q.deleteChaptersByVideoStmt, err = db.PrepareContext(ctx, deleteChaptersByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChaptersByVideo: %w", err)
	}
	if q.deleteTaskDepsByVideoStmt, err = db.PrepareContext(ctx, deleteTaskDepsByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTaskDepsByVideo: %w", err)
	}
	if q.deleteTasksByVideoStmt, err = db.PrepareContext(ctx, deleteTasksByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTasksByVideo: %w", err)
	}
	if q.deleteVideoStmt, err = db.PrepareContext(ctx, deleteVideo); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVideo: %w", err)
	}
	if q.getAssetByIDStmt, err = db.PrepareContext(ctx, getAssetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssetByID: %w", err)
	}
	if q.getChannelByIDStmt, err = db.PrepareContext(ctx, getChannelByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChannelByID: %w", err)
	}
	if q.getChannelBySlugStmt, err = db.PrepareContext(ctx, getChannelBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetChannelBySlug: %w", err)
	}
	if q.getChapterByIDStmt, err = db.PrepareContext(ctx, getChapterByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChapterByID: %w", err)
	}
	if q.getSettingStmt, err = db.PrepareContext(ctx, getSetting); err != nil {
		return nil, fmt.Errorf("error preparing query GetSetting: %w", err)
	}
	if q.getTaskByIDStmt, err = db.PrepareContext(ctx, getTaskByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskByID: %w", err)
	}
	if q.getVideoByIDStmt, err = db.PrepareContext(ctx, getVideoByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideoByID: %w", err)
	}
	if q.getVideoByRefStmt, err = db.PrepareContext(ctx, getVideoByRef); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideoByRef: %w", err)
	}
	if q.getVideoSeqStmt, err = db.PrepareContext(ctx, getVideoSeq); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideoSeq: %w", err)
	}
	if q.incrementVideoSeqStmt, err = db.PrepareContext(ctx, incrementVideoSeq); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementVideoSeq: %w", err)
	}
	if q.insertTaskStmt, err = db.PrepareContext(ctx, insertTask); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTask: %w", err)
	}
	if q.insertTaskDepStmt, err = db.PrepareContext(ctx, insertTaskDep); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTaskDep: %w", err)
	}
	if q.listAssetAddressesStmt, err = db.PrepareContext(ctx, listAssetAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssetAddresses: %w", err)
	}
	if q.listAssetsByVideoStmt, err = db.PrepareContext(ctx, listAssetsByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssetsByVideo: %w", err)
	}
	if q.listChannelsStmt, err = db.PrepareContext(ctx, listChannels); err != nil {
		return nil, fmt.Errorf("error preparing query ListChannels: %w", err)
	}
	if q.listChaptersByVideoStmt, err = db.PrepareContext(ctx, listChaptersByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query ListChaptersByVideo: %w", err)
	}
	if q.listMissingAssetOwnersStmt, err = db.PrepareContext(ctx, listMissingAssetOwners); err != nil {
		return nil, fmt.Errorf("error preparing query ListMissingAssetOwners: %w", err)
	}
	if q.listRecentTasksStmt, err = db.PrepareContext(ctx, listRecentTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentTasks: %w", err)
	}
	if q.listSettingsStmt, err = db.PrepareContext(ctx, listSettings); err != nil {
		return nil, fmt.Errorf("error preparing query ListSettings: %w", err)
	}
	if q.listStaleTasksByVideoStmt, err = db.PrepareContext(ctx, listStaleTasksByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query ListStaleTasksByVideo: %w", err)
	}
	if q.listTaskDepsByVideoStmt, err = db.PrepareContext(ctx, listTaskDepsByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query ListTaskDepsByVideo: %w", err)
	}
	if q.listTasksByVideoStmt, err = db.PrepareContext(ctx, listTasksByVideo); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByVideo: %w", err)
	}
	if q.listVideosStmt, err = db.PrepareContext(ctx, listVideos); err != nil {
		return nil, fmt.Errorf("error preparing query ListVideos: %w", err)
	}
	if q.listVideosWithOpenTasksStmt, err = db.PrepareContext(ctx, listVideosWithOpenTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListVideosWithOpenTasks: %w", err)
	}
	if q.putAssetStmt, err = db.PrepareContext(ctx, putAsset); err != nil {
		return nil, fmt.Errorf("error preparing query PutAsset: %w", err)
	}
	if q.setChapterAudioStmt, err = db.PrepareContext(ctx, setChapterAudio); err != nil {
		return nil, fmt.Errorf("error preparing query SetChapterAudio: %w", err)
	}
	if q.setChapterClipStmt, err = db.PrepareContext(ctx, setChapterClip); err != nil {
		return nil, fmt.Errorf("error preparing query SetChapterClip: %w", err)
	}
	if q.setChapterImageStmt, err = db.PrepareContext(ctx, setChapterImage); err != nil {
		return nil, fmt.Errorf("error preparing query SetChapterImage: %w", err)
	}
	if q.setChapterPromptsStmt, err = db.PrepareContext(ctx, setChapterPrompts); err != nil {
		return nil, fmt.Errorf("error preparing query SetChapterPrompts: %w", err)
	}
	if q.setChapterScriptStmt, err = db.PrepareContext(ctx, setChapterScript); err != nil {
		return nil, fmt.Errorf("error preparing query SetChapterScript: %w", err)
	}
	if q.setVideoBlueprintAssetStmt, err = db.PrepareContext(ctx, setVideoBlueprintAsset); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoBlueprintAsset: %w", err)
	}
	if q.setVideoFinalAssetStmt, err = db.PrepareContext(ctx, setVideoFinalAsset); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoFinalAsset: %w", err)
	}
	if q.setVideoMetadataStmt, err = db.PrepareContext(ctx, setVideoMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoMetadata: %w", err)
	}
	if q.setVideoStateStmt, err = db.PrepareContext(ctx, setVideoState); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoState: %w", err)
	}
	if q.setVideoThumbnailAssetStmt, err = db.PrepareContext(ctx, setVideoThumbnailAsset); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoThumbnailAsset: %w", err)
	}
	if q.setVideoUploadStmt, err = db.PrepareContext(ctx, setVideoUpload); err != nil {
		return nil, fmt.Errorf("error preparing query SetVideoUpload: %w", err)
	}
	if q.updateChannelStmt, err = db.PrepareContext(ctx, updateChannel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChannel: %w", err)
	}
	if q.updateSettingValueStmt, err = db.PrepareContext(ctx, updateSettingValue); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSettingValue: %w", err)
	}
	if q.updateVideoStmt, err = db.PrepareContext(ctx, updateVideo); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateVideo: %w", err)
	}
	if q.upsertChannelBySlugStmt, err = db.PrepareContext(ctx, upsertChannelBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertChannelBySlug: %w", err)
	}
	if q.upsertChapterStmt, err = db.PrepareContext(ctx, upsertChapter); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertChapter: %w", err)
	}
	if q.upsertSettingStmt, err = db.PrepareContext(ctx, upsertSetting); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSetting: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.applyTaskTransitionStmt != nil {
		if cerr := q.applyTaskTransitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing applyTaskTransitionStmt: %w", cerr)
		}
	}
	if q.countAssetOwnersStmt != nil {
		if cerr := q.countAssetOwnersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAssetOwnersStmt: %w", cerr)
		}
	}
	if q.countTasksByVideoStmt != nil {
		if cerr := q.countTasksByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTasksByVideoStmt: %w", cerr)
		}
	}
	if q.countVideosStmt != nil {
		if cerr := q.countVideosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countVideosStmt: %w", cerr)
		}
	}
	if q.createChannelStmt != nil {
		if cerr := q.createChannelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChannelStmt: %w", cerr)
		}
	}
	if q.createVideoStmt != nil {
		if cerr := q.createVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createVideoStmt: %w", cerr)
		}
	}
	if q.deleteChannelStmt != nil {
		if cerr := q.deleteChannelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChannelStmt: %w", cerr)
		}
	}
	if q.deleteChaptersByVideoStmt != nil {
		if cerr := q.deleteChaptersByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChaptersByVideoStmt: %w", cerr)
		}
	}
	if q.deleteTaskDepsByVideoStmt != nil {
		if cerr := q.deleteTaskDepsByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTaskDepsByVideoStmt: %w", cerr)
		}
	}
	if q.deleteTasksByVideoStmt != nil {
		if cerr := q.deleteTasksByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTasksByVideoStmt: %w", cerr)
		}
	}
	if q.deleteVideoStmt != nil {
		if cerr := q.deleteVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVideoStmt: %w", cerr)
		}
	}
	if q.getAssetByIDStmt != nil {
		if cerr := q.getAssetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssetByIDStmt: %w", cerr)
		}
	}
	if q.getChannelByIDStmt != nil {
		if cerr := q.getChannelByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChannelByIDStmt: %w", cerr)
		}
	}
	if q.getChannelBySlugStmt != nil {
		if cerr := q.getChannelBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChannelBySlugStmt: %w", cerr)
		}
	}
	if q.getChapterByIDStmt != nil {
		if cerr := q.getChapterByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChapterByIDStmt: %w", cerr)
		}
	}
	if q.getSettingStmt != nil {
		if cerr := q.getSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSettingStmt: %w", cerr)
		}
	}
	if q.getTaskByIDStmt != nil {
		if cerr := q.getTaskByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskByIDStmt: %w", cerr)
		}
	}
	if q.getVideoByIDStmt != nil {
		if cerr := q.getVideoByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideoByIDStmt: %w", cerr)
		}
	}
	if q.getVideoByRefStmt != nil {
		if cerr := q.getVideoByRefStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideoByRefStmt: %w", cerr)
		}
	}
	if q.getVideoSeqStmt != nil {
		if cerr := q.getVideoSeqStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideoSeqStmt: %w", cerr)
		}
	}
	if q.incrementVideoSeqStmt != nil {
		if cerr := q.incrementVideoSeqStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementVideoSeqStmt: %w", cerr)
		}
	}
	if q.insertTaskStmt != nil {
		if cerr := q.insertTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTaskStmt: %w", cerr)
		}
	}
	if q.insertTaskDepStmt != nil {
		if cerr := q.insertTaskDepStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTaskDepStmt: %w", cerr)
		}
	}
	if q.listAssetAddressesStmt != nil {
		if cerr := q.listAssetAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetAddressesStmt: %w", cerr)
		}
	}
	if q.listAssetsByVideoStmt != nil {
		if cerr := q.listAssetsByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetsByVideoStmt: %w", cerr)
		}
	}
	if q.listChannelsStmt != nil {
		if cerr := q.listChannelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listChannelsStmt: %w", cerr)
		}
	}
	if q.listChaptersByVideoStmt != nil {
		if cerr := q.listChaptersByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listChaptersByVideoStmt: %w", cerr)
		}
	}
	if q.listMissingAssetOwnersStmt != nil {
		if cerr := q.listMissingAssetOwnersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMissingAssetOwnersStmt: %w", cerr)
		}
	}
	if q.listRecentTasksStmt != nil {
		if cerr := q.listRecentTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentTasksStmt: %w", cerr)
		}
	}
	if q.listSettingsStmt != nil {
		if cerr := q.listSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSettingsStmt: %w", cerr)
		}
	}
	if q.listStaleTasksByVideoStmt != nil {
		if cerr := q.listStaleTasksByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStaleTasksByVideoStmt: %w", cerr)
		}
	}
	if q.listTaskDepsByVideoStmt != nil {
		if cerr := q.listTaskDepsByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTaskDepsByVideoStmt: %w", cerr)
		}
	}
	if q.listTasksByVideoStmt != nil {
		if cerr := q.listTasksByVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByVideoStmt: %w", cerr)
		}
	}
	if q.listVideosStmt != nil {
		if cerr := q.listVideosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVideosStmt: %w", cerr)
		}
	}
	if q.listVideosWithOpenTasksStmt != nil {
		if cerr := q.listVideosWithOpenTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVideosWithOpenTasksStmt: %w", cerr)
		}
	}
	if q.putAssetStmt != nil {
		if cerr := q.putAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing putAssetStmt: %w", cerr)
		}
	}
	if q.setChapterAudioStmt != nil {
		if cerr := q.setChapterAudioStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setChapterAudioStmt: %w", cerr)
		}
	}
	if q.setChapterClipStmt != nil {
		if cerr := q.setChapterClipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setChapterClipStmt: %w", cerr)
		}
	}
	if q.setChapterImageStmt != nil {
		if cerr := q.setChapterImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setChapterImageStmt: %w", cerr)
		}
	}
	if q.setChapterPromptsStmt != nil {
		if cerr := q.setChapterPromptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setChapterPromptsStmt: %w", cerr)
		}
	}
	if q.setChapterScriptStmt != nil {
		if cerr := q.setChapterScriptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setChapterScriptStmt: %w", cerr)
		}
	}
	if q.setVideoBlueprintAssetStmt != nil {
		if cerr := q.setVideoBlueprintAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoBlueprintAssetStmt: %w", cerr)
		}
	}
	if q.setVideoFinalAssetStmt != nil {
		if cerr := q.setVideoFinalAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoFinalAssetStmt: %w", cerr)
		}
	}
	if q.setVideoMetadataStmt != nil {
		if cerr := q.setVideoMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoMetadataStmt: %w", cerr)
		}
	}
	if q.setVideoStateStmt != nil {
		if cerr := q.setVideoStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoStateStmt: %w", cerr)
		}
	}
	if q.setVideoThumbnailAssetStmt != nil {
		if cerr := q.setVideoThumbnailAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoThumbnailAssetStmt: %w", cerr)
		}
	}
	if q.setVideoUploadStmt != nil {
		if cerr := q.setVideoUploadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setVideoUploadStmt: %w", cerr)
		}
	}
	if q.updateChannelStmt != nil {
		if cerr := q.updateChannelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChannelStmt: %w", cerr)
		}
	}
	if q.updateSettingValueStmt != nil {
		if cerr := q.updateSettingValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSettingValueStmt: %w", cerr)
		}
	}
	if q.updateVideoStmt != nil {
		if cerr := q.updateVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateVideoStmt: %w", cerr)
		}
	}
	if q.upsertChannelBySlugStmt != nil {
		if cerr := q.upsertChannelBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertChannelBySlugStmt: %w", cerr)
		}
	}
	if q.upsertChapterStmt != nil {
		if cerr := q.upsertChapterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertChapterStmt: %w", cerr)
		}
	}
	if q.upsertSettingStmt != nil {
		if cerr := q.upsertSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSettingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	applyTaskTransitionStmt     *sql.Stmt
	countAssetOwnersStmt        *sql.Stmt
	countTasksByVideoStmt       *sql.Stmt
	countVideosStmt             *sql.Stmt
	createChannelStmt           *sql.Stmt
	createVideoStmt             *sql.Stmt
	deleteChannelStmt           *sql.Stmt
	deleteChaptersByVideoStmt   *sql.Stmt
	deleteTaskDepsByVideoStmt   *sql.Stmt
	deleteTasksByVideoStmt      *sql.Stmt
	deleteVideoStmt             *sql.Stmt
	getAssetByIDStmt            *sql.Stmt
	getChannelByIDStmt          *sql.Stmt
	getChannelBySlugStmt        *sql.Stmt
	getChapterByIDStmt          *sql.Stmt
	getSettingStmt              *sql.Stmt
	getTaskByIDStmt             *sql.Stmt
	getVideoByIDStmt            *sql.Stmt
	getVideoByRefStmt           *sql.Stmt
	getVideoSeqStmt             *sql.Stmt
	incrementVideoSeqStmt       *sql.Stmt
	insertTaskStmt              *sql.Stmt
	insertTaskDepStmt           *sql.Stmt
	listAssetAddressesStmt      *sql.Stmt
	listAssetsByVideoStmt       *sql.Stmt
	listChannelsStmt            *sql.Stmt
	listChaptersByVideoStmt     *sql.Stmt
	listMissingAssetOwnersStmt  *sql.Stmt
	listRecentTasksStmt         *sql.Stmt
	listSettingsStmt            *sql.Stmt
	listStaleTasksByVideoStmt   *sql.Stmt
	listTaskDepsByVideoStmt     *sql.Stmt
	listTasksByVideoStmt        *sql.Stmt
	listVideosStmt              *sql.Stmt
	listVideosWithOpenTasksStmt *sql.Stmt
	putAssetStmt                *sql.Stmt
	setChapterAudioStmt         *sql.Stmt
	setChapterClipStmt          *sql.Stmt
	setChapterImageStmt         *sql.Stmt
	setChapterPromptsStmt       *sql.Stmt
	setChapterScriptStmt        *sql.Stmt
	setVideoBlueprintAssetStmt  *sql.Stmt
	setVideoFinalAssetStmt      *sql.Stmt
	setVideoMetadataStmt        *sql.Stmt
	setVideoStateStmt           *sql.Stmt
	setVideoThumbnailAssetStmt  *sql.Stmt
	setVideoUploadStmt          *sql.Stmt
	updateChannelStmt           *sql.Stmt
	updateSettingValueStmt      *sql.Stmt
	updateVideoStmt             *sql.Stmt
	upsertChannelBySlugStmt     *sql.Stmt
	upsertChapterStmt           *sql.Stmt
	upsertSettingStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		applyTaskTransitionStmt:     q.applyTaskTransitionStmt,
		countAssetOwnersStmt:        q.countAssetOwnersStmt,
		countTasksByVideoStmt:       q.countTasksByVideoStmt,
		countVideosStmt:             q.countVideosStmt,
		createChannelStmt:           q.createChannelStmt,
		createVideoStmt:             q.createVideoStmt,
		deleteChannelStmt:           q.deleteChannelStmt,
		deleteChaptersByVideoStmt:   q.deleteChaptersByVideoStmt,
		deleteTaskDepsByVideoStmt:   q.deleteTaskDepsByVideoStmt,
		deleteTasksByVideoStmt:      q.deleteTasksByVideoStmt,
		deleteVideoStmt:             q.deleteVideoStmt,
		getAssetByIDStmt:            q.getAssetByIDStmt,
		getChannelByIDStmt:          q.getChannelByIDStmt,
		getChannelBySlugStmt:        q.getChannelBySlugStmt,
		getChapterByIDStmt:          q.getChapterByIDStmt,
		getSettingStmt:              q.getSettingStmt,
		getTaskByIDStmt:             q.getTaskByIDStmt,
		getVideoByIDStmt:            q.getVideoByIDStmt,
		getVideoByRefStmt:           q.getVideoByRefStmt,
		getVideoSeqStmt:             q.getVideoSeqStmt,
		incrementVideoSeqStmt:       q.incrementVideoSeqStmt,
		insertTaskStmt:              q.insertTaskStmt,
		insertTaskDepStmt:           q.insertTaskDepStmt,
		listAssetAddressesStmt:      q.listAssetAddressesStmt,
		listAssetsByVideoStmt:       q.listAssetsByVideoStmt,
		listChannelsStmt:            q.listChannelsStmt,
		listChaptersByVideoStmt:     q.listChaptersByVideoStmt,
		listMissingAssetOwnersStmt:  q.listMissingAssetOwnersStmt,
		listRecentTasksStmt:         q.listRecentTasksStmt,
		listSettingsStmt:            q.listSettingsStmt,
		listStaleTasksByVideoStmt:   q.listStaleTasksByVideoStmt,
		listTaskDepsByVideoStmt:     q.listTaskDepsByVideoStmt,
		listTasksByVideoStmt:        q.listTasksByVideoStmt,
		listVideosStmt:              q.listVideosStmt,
		listVideosWithOpenTasksStmt: q.listVideosWithOpenTasksStmt,
		putAssetStmt:                q.putAssetStmt,
		setChapterAudioStmt:         q.setChapterAudioStmt,
		setChapterClipStmt:          q.setChapterClipStmt,
		setChapterImageStmt:         q.setChapterImageStmt,
		setChapterPromptsStmt:       q.setChapterPromptsStmt,
		setChapterScriptStmt:        q.setChapterScriptStmt,
		setVideoBlueprintAssetStmt:  q.setVideoBlueprintAssetStmt,
		setVideoFinalAssetStmt:      q.setVideoFinalAssetStmt,
		setVideoMetadataStmt:        q.setVideoMetadataStmt,
		setVideoStateStmt:           q.setVideoStateStmt,
		setVideoThumbnailAssetStmt:  q.setVideoThumbnailAssetStmt,
		setVideoUploadStmt:          q.setVideoUploadStmt,
		updateChannelStmt:           q.updateChannelStmt,
		updateSettingValueStmt:      q.updateSettingValueStmt,
		updateVideoStmt:             q.updateVideoStmt,
		upsertChannelBySlugStmt:     q.upsertChannelBySlugStmt,
		upsertChapterStmt:           q.upsertChapterStmt,
		upsertSettingStmt:           q.upsertSettingStmt,
	}
}
