// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Asset struct {
	ID         string
	VideoID    string
	ChapterID  *string
	Kind       string
	Path       string
	Size       int64
	Mime       string
	Provenance string
	CreatedAt  int64
}

type Channel struct {
	ID          string
	Slug        string
	Name        string
	Description string
	Credentials string
	VideoSeq    int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Chapter struct {
	ID                string
	VideoID           string
	Ordinal           int64
	Title             string
	Summary           string
	Script            string
	ImagePromptsJson  string
	AudioAssetID      *string
	ImageAssetIdsJson string
	ClipAssetID       *string
	DurationSeconds   float64
	CreatedAt         int64
	UpdatedAt         int64
	EstimatedWords    int64
}

type Setting struct {
	Key         string
	Value       string
	Type        string
	Grp         string
	Description string
	MinValue    int64
	MaxValue    int64
	UpdatedAt   int64
}

type Task struct {
	ID            string
	VideoID       string
	ChapterID     *string
	Kind          string
	Ordinal       int64
	Idx           int64
	State         string
	Pool          string
	Gate          string
	Attempt       int64
	MaxAttempts   int64
	DepsRemaining int64
	Error         string
	CreatedAt     int64
	UpdatedAt     int64
	StartedAt     *int64
	FinishedAt    *int64
	NotBefore     *int64
	Stale         int64
}

type TaskDep struct {
	VideoID string
	FromID  string
	ToID    string
}

type Video struct {
	ID                    string
	ChannelID             string
	Ref                   string
	Title                 string
	Topic                 string
	State                 string
	ChapterCount          int64
	ImagesPerChapter      int64
	BlueprintAssetID      *string
	FinalAssetID          *string
	MetadataJson          *string
	UploadJson            *string
	Error                 string
	CreatedAt             int64
	UpdatedAt             int64
	StartedAt             *int64
	CompletedAt           *int64
	TargetDurationMinutes int64
	ThumbnailAssetID      *string
	ThumbnailCells        int64
	ThumbnailPlanJson     *string
	ThumbnailIconIdsJson  string
}
