// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT "key", value, type, grp, description, min_value, max_value, updated_at FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingStmt, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Grp,
		&i.Description,
		&i.MinValue,
		&i.MaxValue,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, type, grp, description, min_value, max_value, updated_at FROM settings ORDER BY grp, key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.query(ctx, q.listSettingsStmt, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Type,
			&i.Grp,
			&i.Description,
			&i.MinValue,
			&i.MaxValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingValue = `-- name: UpdateSettingValue :exec
UPDATE settings SET value = ?, updated_at = ? WHERE key = ?
`

type UpdateSettingValueParams struct {
	Value     string
	UpdatedAt int64
	Key       string
}

func (q *Queries) UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error {
	_, err := q.exec(ctx, q.updateSettingValueStmt, updateSettingValue, arg.Value, arg.UpdatedAt, arg.Key)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, type, grp, description, min_value, max_value, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    type = excluded.type,
    grp = excluded.grp,
    description = excluded.description,
    min_value = excluded.min_value,
    max_value = excluded.max_value
`

type UpsertSettingParams struct {
	Key         string
	Value       string
	Type        string
	Grp         string
	Description string
	MinValue    int64
	MaxValue    int64
	UpdatedAt   int64
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.exec(ctx, q.upsertSettingStmt, upsertSetting,
		arg.Key,
		arg.Value,
		arg.Type,
		arg.Grp,
		arg.Description,
		arg.MinValue,
		arg.MaxValue,
		arg.UpdatedAt,
	)
	return err
}
