// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
)

const applyTaskTransition = `-- name: ApplyTaskTransition :exec
UPDATE tasks
SET state = ?, attempt = ?, deps_remaining = ?, error = ?, stale = ?,
    started_at = ?, finished_at = ?, not_before = ?, updated_at = ?
WHERE id = ?
`

type ApplyTaskTransitionParams struct {
	State         string
	Attempt       int64
	DepsRemaining int64
	Error         string
	Stale         int64
	StartedAt     *int64
	FinishedAt    *int64
	NotBefore     *int64
	UpdatedAt     int64
	ID            string
}

func (q *Queries) ApplyTaskTransition(ctx context.Context, arg ApplyTaskTransitionParams) error {
	_, err := q.exec(ctx, q.applyTaskTransitionStmt, applyTaskTransition,
		arg.State,
		arg.Attempt,
		arg.DepsRemaining,
		arg.Error,
		arg.Stale,
		arg.StartedAt,
		arg.FinishedAt,
		arg.NotBefore,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countTasksByVideo = `-- name: CountTasksByVideo :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN state = 'succeeded' THEN 1 ELSE 0 END), 0) AS INTEGER) AS succeeded,
    CAST(COALESCE(SUM(CASE WHEN state = 'failed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed,
    CAST(COALESCE(SUM(CASE WHEN state = 'running' THEN 1 ELSE 0 END), 0) AS INTEGER) AS running,
    CAST(COALESCE(SUM(CASE WHEN state = 'ready' THEN 1 ELSE 0 END), 0) AS INTEGER) AS ready,
    CAST(COALESCE(SUM(CASE WHEN state = 'blocked' THEN 1 ELSE 0 END), 0) AS INTEGER) AS blocked,
    CAST(COALESCE(SUM(CASE WHEN state = 'awaiting_approval' THEN 1 ELSE 0 END), 0) AS INTEGER) AS awaiting,
    CAST(COALESCE(SUM(CASE WHEN state = 'cancelled' THEN 1 ELSE 0 END), 0) AS INTEGER) AS cancelled,
    CAST(COALESCE(SUM(CASE WHEN stale = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS stale
FROM tasks WHERE video_id = ?
`

type CountTasksByVideoRow struct {
	Total     int64
	Succeeded int64
	Failed    int64
	Running   int64
	Ready     int64
	Blocked   int64
	Awaiting  int64
	Cancelled int64
	Stale     int64
}

func (q *Queries) CountTasksByVideo(ctx context.Context, videoID string) (CountTasksByVideoRow, error) {
	row := q.queryRow(ctx, q.countTasksByVideoStmt, countTasksByVideo, videoID)
	var i CountTasksByVideoRow
	err := row.Scan(
		&i.Total,
		&i.Succeeded,
		&i.Failed,
		&i.Running,
		&i.Ready,
		&i.Blocked,
		&i.Awaiting,
		&i.Cancelled,
		&i.Stale,
	)
	return i, err
}

const deleteTaskDepsByVideo = `-- name: DeleteTaskDepsByVideo :exec
DELETE FROM task_deps WHERE video_id = ?
`

func (q *Queries) DeleteTaskDepsByVideo(ctx context.Context, videoID string) error {
	_, err := q.exec(ctx, q.deleteTaskDepsByVideoStmt, deleteTaskDepsByVideo, videoID)
	return err
}

const deleteTasksByVideo = `-- name: DeleteTasksByVideo :exec
DELETE FROM tasks WHERE video_id = ?
`

func (q *Queries) DeleteTasksByVideo(ctx context.Context, videoID string) error {
	_, err := q.exec(ctx, q.deleteTasksByVideoStmt, deleteTasksByVideo, videoID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, video_id, chapter_id, kind, ordinal, idx, state, pool, gate, attempt, max_attempts, deps_remaining, error, created_at, updated_at, started_at, finished_at, not_before, stale FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.queryRow(ctx, q.getTaskByIDStmt, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChapterID,
		&i.Kind,
		&i.Ordinal,
		&i.Idx,
		&i.State,
		&i.Pool,
		&i.Gate,
		&i.Attempt,
		&i.MaxAttempts,
		&i.DepsRemaining,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NotBefore,
		&i.Stale,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (
    id, video_id, chapter_id, kind, ordinal, idx, state, pool, gate,
    attempt, max_attempts, deps_remaining, error, stale,
    created_at, updated_at, started_at, finished_at, not_before
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type InsertTaskParams struct {
	ID            string
	VideoID       string
	ChapterID     *string
	Kind          string
	Ordinal       int64
	Idx           int64
	State         string
	Pool          string
	Gate          string
	Attempt       int64
	MaxAttempts   int64
	DepsRemaining int64
	Error         string
	Stale         int64
	CreatedAt     int64
	UpdatedAt     int64
	StartedAt     *int64
	FinishedAt    *int64
	NotBefore     *int64
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.exec(ctx, q.insertTaskStmt, insertTask,
		arg.ID,
		arg.VideoID,
		arg.ChapterID,
		arg.Kind,
		arg.Ordinal,
		arg.Idx,
		arg.State,
		arg.Pool,
		arg.Gate,
		arg.Attempt,
		arg.MaxAttempts,
		arg.DepsRemaining,
		arg.Error,
		arg.Stale,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.NotBefore,
	)
	return err
}

const insertTaskDep = `-- name: InsertTaskDep :exec
INSERT INTO task_deps (video_id, from_id, to_id) VALUES (?, ?, ?)
ON CONFLICT (from_id, to_id) DO NOTHING
`

type InsertTaskDepParams struct {
	VideoID string
	FromID  string
	ToID    string
}

func (q *Queries) InsertTaskDep(ctx context.Context, arg InsertTaskDepParams) error {
	_, err := q.exec(ctx, q.insertTaskDepStmt, insertTaskDep, arg.VideoID, arg.FromID, arg.ToID)
	return err
}

const listRecentTasks = `-- name: ListRecentTasks :many
SELECT id, video_id, chapter_id, kind, ordinal, idx, state, pool, gate, attempt, max_attempts, deps_remaining, error, created_at, updated_at, started_at, finished_at, not_before, stale FROM tasks ORDER BY updated_at DESC LIMIT ?
`

func (q *Queries) ListRecentTasks(ctx context.Context, limit int64) ([]Task, error) {
	rows, err := q.query(ctx, q.listRecentTasksStmt, listRecentTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChapterID,
			&i.Kind,
			&i.Ordinal,
			&i.Idx,
			&i.State,
			&i.Pool,
			&i.Gate,
			&i.Attempt,
			&i.MaxAttempts,
			&i.DepsRemaining,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NotBefore,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleTasksByVideo = `-- name: ListStaleTasksByVideo :many
SELECT id, video_id, chapter_id, kind, ordinal, idx, state, pool, gate, attempt, max_attempts, deps_remaining, error, created_at, updated_at, started_at, finished_at, not_before, stale FROM tasks WHERE video_id = ? AND stale = 1 ORDER BY ordinal, idx, kind
`

func (q *Queries) ListStaleTasksByVideo(ctx context.Context, videoID string) ([]Task, error) {
	rows, err := q.query(ctx, q.listStaleTasksByVideoStmt, listStaleTasksByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChapterID,
			&i.Kind,
			&i.Ordinal,
			&i.Idx,
			&i.State,
			&i.Pool,
			&i.Gate,
			&i.Attempt,
			&i.MaxAttempts,
			&i.DepsRemaining,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NotBefore,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDepsByVideo = `-- name: ListTaskDepsByVideo :many
SELECT video_id, from_id, to_id FROM task_deps WHERE video_id = ?
`

func (q *Queries) ListTaskDepsByVideo(ctx context.Context, videoID string) ([]TaskDep, error) {
	rows, err := q.query(ctx, q.listTaskDepsByVideoStmt, listTaskDepsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDep{}
	for rows.Next() {
		var i TaskDep
		if err := rows.Scan(&i.VideoID, &i.FromID, &i.ToID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByVideo = `-- name: ListTasksByVideo :many
SELECT id, video_id, chapter_id, kind, ordinal, idx, state, pool, gate, attempt, max_attempts, deps_remaining, error, created_at, updated_at, started_at, finished_at, not_before, stale FROM tasks WHERE video_id = ? ORDER BY ordinal, idx, kind
`

func (q *Queries) ListTasksByVideo(ctx context.Context, videoID string) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByVideoStmt, listTasksByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChapterID,
			&i.Kind,
			&i.Ordinal,
			&i.Idx,
			&i.State,
			&i.Pool,
			&i.Gate,
			&i.Attempt,
			&i.MaxAttempts,
			&i.DepsRemaining,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NotBefore,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosWithOpenTasks = `-- name: ListVideosWithOpenTasks :many
SELECT DISTINCT video_id FROM tasks
WHERE state IN ('blocked', 'ready', 'running', 'awaiting_approval')
`

func (q *Queries) ListVideosWithOpenTasks(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listVideosWithOpenTasksStmt, listVideosWithOpenTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var video_id string
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
