// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlcgen

import (
	"context"
)

const countVideos = `-- name: CountVideos :one
SELECT COUNT(*) FROM videos
WHERE (CAST(?1 AS TEXT) = '' OR channel_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR state = ?2)
`

type CountVideosParams struct {
	ChannelID string
	State     string
}

func (q *Queries) CountVideos(ctx context.Context, arg CountVideosParams) (int64, error) {
	row := q.queryRow(ctx, q.countVideosStmt, countVideos, arg.ChannelID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :exec
INSERT INTO videos (
    id, channel_id, ref, title, topic, state, chapter_count, images_per_chapter,
    target_duration_minutes, blueprint_asset_id, final_asset_id, thumbnail_asset_id,
    metadata_json, upload_json, error, created_at, updated_at, started_at, completed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVideoParams struct {
	ID                    string
	ChannelID             string
	Ref                   string
	Title                 string
	Topic                 string
	State                 string
	ChapterCount          int64
	ImagesPerChapter      int64
	TargetDurationMinutes int64
	BlueprintAssetID      *string
	FinalAssetID          *string
	ThumbnailAssetID      *string
	MetadataJson          *string
	UploadJson            *string
	Error                 string
	CreatedAt             int64
	UpdatedAt             int64
	StartedAt             *int64
	CompletedAt           *int64
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.exec(ctx, q.createVideoStmt, createVideo,
		arg.ID,
		arg.ChannelID,
		arg.Ref,
		arg.Title,
		arg.Topic,
		arg.State,
		arg.ChapterCount,
		arg.ImagesPerChapter,
		arg.TargetDurationMinutes,
		arg.BlueprintAssetID,
		arg.FinalAssetID,
		arg.ThumbnailAssetID,
		arg.MetadataJson,
		arg.UploadJson,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteVideoStmt, deleteVideo, id)
	return err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, channel_id, ref, title, topic, state, chapter_count, images_per_chapter, blueprint_asset_id, final_asset_id, metadata_json, upload_json, error, created_at, updated_at, started_at, completed_at, target_duration_minutes, thumbnail_asset_id FROM videos WHERE id = ?
`

func (q *Queries) GetVideoByID(ctx context.Context, id string) (Video, error) {
	row := q.queryRow(ctx, q.getVideoByIDStmt, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Ref,
		&i.Title,
		&i.Topic,
		&i.State,
		&i.ChapterCount,
		&i.ImagesPerChapter,
		&i.BlueprintAssetID,
		&i.FinalAssetID,
		&i.MetadataJson,
		&i.UploadJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TargetDurationMinutes,
		&i.ThumbnailAssetID,
	)
	return i, err
}

const getVideoByRef = `-- name: GetVideoByRef :one
SELECT id, channel_id, ref, title, topic, state, chapter_count, images_per_chapter, blueprint_asset_id, final_asset_id, metadata_json, upload_json, error, created_at, updated_at, started_at, completed_at, target_duration_minutes, thumbnail_asset_id FROM videos WHERE ref = ?
`

func (q *Queries) GetVideoByRef(ctx context.Context, ref string) (Video, error) {
	row := q.queryRow(ctx, q.getVideoByRefStmt, getVideoByRef, ref)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Ref,
		&i.Title,
		&i.Topic,
		&i.State,
		&i.ChapterCount,
		&i.ImagesPerChapter,
		&i.BlueprintAssetID,
		&i.FinalAssetID,
		&i.MetadataJson,
		&i.UploadJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TargetDurationMinutes,
		&i.ThumbnailAssetID,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, channel_id, ref, title, topic, state, chapter_count, images_per_chapter, blueprint_asset_id, final_asset_id, metadata_json, upload_json, error, created_at, updated_at, started_at, completed_at, target_duration_minutes, thumbnail_asset_id FROM videos
WHERE (CAST(?1 AS TEXT) = '' OR channel_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR state = ?2)
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListVideosParams struct {
	ChannelID string
	State     string
	Off       int64
	Lim       int64
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.query(ctx, q.listVideosStmt, listVideos,
		arg.ChannelID,
		arg.State,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Ref,
			&i.Title,
			&i.Topic,
			&i.State,
			&i.ChapterCount,
			&i.ImagesPerChapter,
			&i.BlueprintAssetID,
			&i.FinalAssetID,
			&i.MetadataJson,
			&i.UploadJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TargetDurationMinutes,
			&i.ThumbnailAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoBlueprintAsset = `-- name: SetVideoBlueprintAsset :exec
UPDATE videos SET blueprint_asset_id = ?, updated_at = ? WHERE id = ?
`

type SetVideoBlueprintAssetParams struct {
	BlueprintAssetID *string
	UpdatedAt        int64
	ID               string
}

func (q *Queries) SetVideoBlueprintAsset(ctx context.Context, arg SetVideoBlueprintAssetParams) error {
	_, err := q.exec(ctx, q.setVideoBlueprintAssetStmt, setVideoBlueprintAsset, arg.BlueprintAssetID, arg.UpdatedAt, arg.ID)
	return err
}

const setVideoFinalAsset = `-- name: SetVideoFinalAsset :exec
UPDATE videos SET final_asset_id = ?, updated_at = ? WHERE id = ?
`

type SetVideoFinalAssetParams struct {
	FinalAssetID *string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) SetVideoFinalAsset(ctx context.Context, arg SetVideoFinalAssetParams) error {
	_, err := q.exec(ctx, q.setVideoFinalAssetStmt, setVideoFinalAsset, arg.FinalAssetID, arg.UpdatedAt, arg.ID)
	return err
}

const setVideoMetadata = `-- name: SetVideoMetadata :exec
UPDATE videos SET metadata_json = ?, updated_at = ? WHERE id = ?
`

type SetVideoMetadataParams struct {
	MetadataJson *string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) SetVideoMetadata(ctx context.Context, arg SetVideoMetadataParams) error {
	_, err := q.exec(ctx, q.setVideoMetadataStmt, setVideoMetadata, arg.MetadataJson, arg.UpdatedAt, arg.ID)
	return err
}

const setVideoState = `-- name: SetVideoState :exec
UPDATE videos
SET state = ?,
    error = ?,
    updated_at = ?,
    started_at = COALESCE(started_at, ?),
    completed_at = ?
WHERE id = ?
`

type SetVideoStateParams struct {
	State       string
	Error       string
	UpdatedAt   int64
	StartedAt   *int64
	CompletedAt *int64
	ID          string
}

func (q *Queries) SetVideoState(ctx context.Context, arg SetVideoStateParams) error {
	_, err := q.exec(ctx, q.setVideoStateStmt, setVideoState,
		arg.State,
		arg.Error,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const setVideoThumbnailAsset = `-- name: SetVideoThumbnailAsset :exec
UPDATE videos SET thumbnail_asset_id = ?, updated_at = ? WHERE id = ?
`

type SetVideoThumbnailAssetParams struct {
	ThumbnailAssetID *string
	UpdatedAt        int64
	ID               string
}

func (q *Queries) SetVideoThumbnailAsset(ctx context.Context, arg SetVideoThumbnailAssetParams) error {
	_, err := q.exec(ctx, q.setVideoThumbnailAssetStmt, setVideoThumbnailAsset, arg.ThumbnailAssetID, arg.UpdatedAt, arg.ID)
	return err
}

const setVideoUpload = `-- name: SetVideoUpload :exec
UPDATE videos SET upload_json = ?, updated_at = ? WHERE id = ?
`

type SetVideoUploadParams struct {
	UploadJson *string
	UpdatedAt  int64
	ID         string
}

func (q *Queries) SetVideoUpload(ctx context.Context, arg SetVideoUploadParams) error {
	_, err := q.exec(ctx, q.setVideoUploadStmt, setVideoUpload, arg.UploadJson, arg.UpdatedAt, arg.ID)
	return err
}

const updateVideo = `-- name: UpdateVideo :exec
UPDATE videos
SET title = ?, topic = ?, state = ?, chapter_count = ?, images_per_chapter = ?,
    target_duration_minutes = ?,
    blueprint_asset_id = ?, final_asset_id = ?, thumbnail_asset_id = ?,
    metadata_json = ?, upload_json = ?, error = ?, updated_at = ?,
    started_at = ?, completed_at = ?
WHERE id = ?
`

type UpdateVideoParams struct {
	Title                 string
	Topic                 string
	State                 string
	ChapterCount          int64
	ImagesPerChapter      int64
	TargetDurationMinutes int64
	BlueprintAssetID      *string
	FinalAssetID          *string
	ThumbnailAssetID      *string
	MetadataJson          *string
	UploadJson            *string
	Error                 string
	UpdatedAt             int64
	StartedAt             *int64
	CompletedAt           *int64
	ID                    string
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.exec(ctx, q.updateVideoStmt, updateVideo,
		arg.Title,
		arg.Topic,
		arg.State,
		arg.ChapterCount,
		arg.ImagesPerChapter,
		arg.TargetDurationMinutes,
		arg.BlueprintAssetID,
		arg.FinalAssetID,
		arg.ThumbnailAssetID,
		arg.MetadataJson,
		arg.UploadJson,
		arg.Error,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
