// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as entity$0 from "../../../../tbui/yt-studio/internal/domain/entity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../tbui/yt-studio/internal/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "console:frames": services$0.ConsoleBatch;
            "pipeline:event": entity$0.Event;
            "pipeline:resync": services$0.Resync;
            "system:accessibility": services$0.AccessibilityOptions;
            "update:state": services$0.UpdateState;
        }
    }
}
