// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChannelService lists channels and manages each one's YouTube grant.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Auth reports what a channel can publish with, reconciling its row.
 */
export function Auth(channel: string): $CancellablePromise<$models.ChannelAuthDTO> {
    return $Call.ByID(2245054226, channel);
}

/**
 * AuthURL is the consent page's address.
 */
export function AuthURL(channel: string): $CancellablePromise<string> {
    return $Call.ByID(276024059, channel);
}

/**
 * Authorize exchanges a pasted code (or redirect URL) for a stored grant.
 */
export function Authorize(channel: string, code: string): $CancellablePromise<$models.ChannelAuthDTO> {
    return $Call.ByID(2556603847, channel, code);
}

/**
 * ForgetAuth drops a channel's grant; its OAuth client stays.
 */
export function ForgetAuth(channel: string): $CancellablePromise<$models.ChannelAuthDTO> {
    return $Call.ByID(2905080079, channel);
}

/**
 * List returns every channel.
 */
export function List(): $CancellablePromise<$models.ChannelDTO[] | null> {
    return $Call.ByID(2526729756);
}
