// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChapterService reads and edits a video's chapters.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns a video's chapters in order.
 */
export function List(video: string): $CancellablePromise<$models.ChapterDTO[] | null> {
    return $Call.ByID(1252117294, video);
}

/**
 * RegenerateSlide redraws one slide from an edited prompt.
 */
export function RegenerateSlide(id: string, index: number, prompt: string): $CancellablePromise<$models.ChapterDTO> {
    return $Call.ByID(2394188621, id, index, prompt);
}

/**
 * UpdatePlan edits a chapter's plan. Nothing re-runs.
 */
export function UpdatePlan(id: string, plan: $models.ChapterPlan): $CancellablePromise<$models.ChapterDTO> {
    return $Call.ByID(1232595236, id, plan);
}

/**
 * UpdateScript replaces a chapter's narration, flagging what it produced stale.
 */
export function UpdateScript(id: string, script: string): $CancellablePromise<$models.ChapterDTO> {
    return $Call.ByID(322749884, id, script);
}
