// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleService streams model exchanges only while the console is open.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Close stops sending session's frames.
 */
export function Close(session: number): $CancellablePromise<void> {
    return $Call.ByID(2794442746, session);
}

/**
 * Open streams to session; calls for sessions older than the newest seen are ignored.
 */
export function Open(session: number): $CancellablePromise<void> {
    return $Call.ByID(512641422, session);
}
