// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * AccessibilityOptions are the macOS display settings the UI follows.
 */
export interface AccessibilityOptions {
    "reduceTransparency": boolean;
    "reduceMotion": boolean;
    "increaseContrast": boolean;
}

/**
 * ChannelAuthDTO is what a channel can currently publish with.
 */
export interface ChannelAuthDTO {
    "channel": ChannelDTO;

    /**
     * ClientPresent: an OAuth client is at ClientPath.
     */
    "clientPresent": boolean;
    "status": string;
    "authorized": boolean;
    "scope"?: string;
    "expiry"?: string | null;
    "clientPath"?: string;
}

/**
 * ChannelDTO is a channel as the API presents it.
 */
export interface ChannelDTO {
    "id": string;
    "slug": string;
    "name": string;
    "description": string;
    "style": StyleDTO;
    "credentials": string;
    "videoSeq": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ChapterDTO is a chapter as the API presents it.
 */
export interface ChapterDTO {
    "id": string;
    "videoId": string;
    "ordinal": number;
    "title": string;
    "summary": string;
    "script": string;
    "slidePrompts": string[] | null;
    "audioAssetId"?: string;
    "slideAssetIds": string[] | null;
    "clipAssetId"?: string;
    "audioDurationSeconds": number;
    "estimatedWords": number;
    "updatedAt": string;
}

/**
 * ChapterPlan is what the blueprint plans for a chapter.
 */
export interface ChapterPlan {
    "title": string;
    "summary": string;

    /**
     * EstimatedWords is the spoken-word budget; 0 leaves it unset.
     */
    "estimatedWords": number;
}

/**
 * ConsoleBatch is a ConsoleEvent; a session's first batch is its backlog.
 */
export interface ConsoleBatch {
    "session": number;
    "reset"?: boolean;
    "frames": LLMFrame[] | null;
}

/**
 * Info describes the running app.
 */
export interface Info {
    "version": string;
    "home": string;
}

/**
 * LLMFrame is a run's text so far (backlog) or since the last frame.
 */
export interface LLMFrame {
    "run": number;
    "videoId": string;
    "label": string;
    "model": string;
    "text"?: string;
    "done"?: boolean;
    "error"?: string;
    "truncated"?: boolean;
    "startedAt": string;
    "ms"?: number;
}

/**
 * MetadataDTO is the YouTube-facing listing.
 */
export interface MetadataDTO {
    "title": string;
    "description": string;
    "tags": string[] | null;
    "thumbnailText": string;
    "categoryId": string;
    "privacy": string;
}

/**
 * NewVideo is a video to create; zero counts take the settings' defaults.
 */
export interface NewVideo {
    "channel": string;
    "title": string;
    "topic"?: string;
    "chapterCount"?: number;
    "slidesPerChapter"?: number;
    "thumbnailCells"?: number;
    "targetDurationMinutes"?: number;

    /**
     * Start enqueues the DAG straight away.
     */
    "start"?: boolean;

    /**
     * Blueprint is a prepared outline; the video then skips the blueprint gate.
     */
    "blueprint"?: json$0.RawMessage;
}

/**
 * Republished is what a republish disowned: the video left on YouTube.
 */
export interface Republished {
    "previousUrl": string;
    "previousVideoId": string;
}

/**
 * RerunPlan is what a re-run ran again and what it flagged stale.
 */
export interface RerunPlan {
    "dryRun": boolean;
    "rerun": TaskDTO[] | null;
    "stale": TaskDTO[] | null;
}

/**
 * Resync is the payload of PipelineResyncEvent.
 */
export interface Resync {
}

/**
 * SettingDTO is one runtime configuration row.
 */
export interface SettingDTO {
    "key": string;
    "value": string;
    "type": string;
    "group": string;
    "description": string;
    "min": number;
    "max": number;
    "options": string[] | null;
    "backend": string;
    "suggestions": SettingSuggestionDTO[] | null;
    "secret": boolean;
    "configured": boolean;
    "updatedAt": string;
}

/**
 * SettingSuggestionDTO is one known-good value and the name it goes by.
 */
export interface SettingSuggestionDTO {
    "value": string;
    "label": string;
}

/**
 * StyleDTO is a channel's creative configuration as the API returns it.
 */
export interface StyleDTO {
}

/**
 * TaskCountsDTO is a video's task census.
 */
export interface TaskCountsDTO {
    "total": number;
    "succeeded": number;
    "failed": number;
    "running": number;
    "ready": number;
    "blocked": number;
    "awaitingApproval": number;
    "cancelled": number;

    /**
     * Stale cuts across the counts above; it does not partition with them.
     */
    "stale": number;
}

/**
 * TaskDTO is a task as the API presents it.
 */
export interface TaskDTO {
    "id": string;
    "videoId": string;
    "chapterId"?: string;
    "kind": string;
    "ordinal": number;
    "index": number;
    "state": string;
    "pool": string;
    "gate"?: string;
    "attempt": number;
    "maxAttempts": number;
    "depsRemaining": number;
    "stale": boolean;
    "error"?: string;
    "updatedAt": string;
    "startedAt"?: string | null;
    "finishedAt"?: string | null;
    "notBefore"?: string | null;
}

/**
 * ThumbnailCellDTO is one tile of the grid. Prompt is the subject alone: the
 * shared style clause lives in settings and is appended when the icon is drawn.
 */
export interface ThumbnailCellDTO {
    "caption": string;
    "prompt": string;
}

/**
 * UpdateState is where updating stands. It's the payload of UpdateEvent.
 */
export interface UpdateState {
    "state": string;

    /**
     * Current is the running version.
     */
    "current": string;

    /**
     * Version is the new version (preparing, ready).
     */
    "version"?: string;

    /**
     * Notes are the new version's changes (ready).
     */
    "notes"?: string[] | null;

    /**
     * Error says what failed (failed; ready, when restarting failed).
     */
    "error"?: string;
}

/**
 * UploadDTO is the upload receipt.
 */
export interface UploadDTO {
    "remoteVideoId": string;
    "url": string;
    "dryRun": boolean;
    "uploadedAt": string;
}

/**
 * VideoBrief is a video's editable brief, whole.
 */
export interface VideoBrief {
    "title": string;
    "topic": string;
    "chapterCount": number;
    "slidesPerChapter": number;
    "thumbnailCells": number;
    "targetDurationMinutes": number;
}

/**
 * VideoDTO is a video as the API presents it.
 */
export interface VideoDTO {
    "id": string;
    "channelId": string;
    "ref": string;
    "title": string;
    "topic": string;
    "state": string;
    "chapterCount": number;
    "targetDurationMinutes": number;
    "slidesPerChapter": number;
    "thumbnailCells": number;
    "blueprintAssetId"?: string;
    "finalAssetId"?: string;
    "chapterOffsets": number[] | null;
    "thumbnailAssetId"?: string;
    "thumbnailOverrideAssetId"?: string;
    "effectiveThumbnailAssetId"?: string;
    "thumbnailDesign"?: any;
    "thumbnailPlan": ThumbnailCellDTO[] | null;
    "thumbnailIconIds": string[] | null;
    "metadata"?: MetadataDTO | null;
    "upload"?: UploadDTO | null;
    "error"?: string;
    "counts": TaskCountsDTO;
    "createdAt": string;
    "updatedAt": string;
    "startedAt"?: string | null;
    "completedAt"?: string | null;
}
