// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchedulerService reports what the pipeline is doing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../domain/entity/models.js";

/**
 * Snapshot is the pool table now; PipelineEvent carries it as it changes.
 */
export function Snapshot(): $CancellablePromise<entity$0.SchedulerDelta> {
    return $Call.ByID(2155492382);
}
