// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService reads and writes the runtime settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every setting. Secret values are never returned.
 */
export function List(): $CancellablePromise<$models.SettingDTO[] | null> {
    return $Call.ByID(1074129830);
}

/**
 * Update sets one setting; it applies immediately.
 */
export function Update(key: string, value: string): $CancellablePromise<$models.SettingDTO> {
    return $Call.ByID(863796387, key, value);
}
