// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is the app's bridge to the system.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Accessibility returns the macOS display accessibility settings.
 */
export function Accessibility(): $CancellablePromise<$models.AccessibilityOptions> {
    return $Call.ByID(3754134294);
}

/**
 * Info returns the running version and where its data lives.
 */
export function Info(): $CancellablePromise<$models.Info> {
    return $Call.ByID(395071614);
}

/**
 * OpenURL opens a web link in the default browser.
 */
export function OpenURL(link: string): $CancellablePromise<void> {
    return $Call.ByID(2200324271, link);
}

/**
 * Reveal shows a file or folder in Finder.
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(3350187811, path);
}

/**
 * SetLook applies the theme to the window now; the material applies at the
 * next launch.
 */
export function SetLook(theme: string, material: string): $CancellablePromise<void> {
    return $Call.ByID(1055874749, theme, material);
}
