// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService reads a video's DAG and runs its tasks again.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptStale clears stale flags (no ids: all) and returns how many.
 */
export function AcceptStale(video: string, ids: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(1620033615, video, ids);
}

/**
 * List returns a video's whole DAG.
 */
export function List(video: string): $CancellablePromise<$models.TaskDTO[] | null> {
    return $Call.ByID(1113086574, video);
}

/**
 * Rerun runs succeeded tasks again, flagging downstream tasks stale.
 */
export function Rerun(video: string, ids: string[] | null): $CancellablePromise<$models.RerunPlan> {
    return $Call.ByID(4216891032, video, ids);
}

/**
 * Retry runs a failed task and everything under it again.
 */
export function Retry(id: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(758869344, id);
}
