// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThumbnailService edits a video's thumbnail.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyOverride makes a PNG from the builder the published thumbnail.
 */
export function ApplyOverride(key: string, png: string | null): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(1419657153, key, png);
}

/**
 * ClearOverride reverts to the rendered thumbnail; the design is kept.
 */
export function ClearOverride(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(1985627424, key);
}

/**
 * Push sends a published video's thumbnail to YouTube again.
 */
export function Push(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(764696059, key);
}

/**
 * RegenerateIcon redraws one grid cell from an edited prompt.
 */
export function RegenerateIcon(key: string, index: number, prompt: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(3638891172, key, index, prompt);
}

/**
 * SaveDesign stores the builder's opaque document.
 */
export function SaveDesign(key: string, design: any): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(2561283708, key, design);
}
