// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService keeps a new version ready as soon as one is released, and
 * restarts into it when asked.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check checks for a new version now and prepares it; it returns the
 * resulting state.
 */
export function Check(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(127703366);
}

/**
 * Restart quits and relaunches into the new version. Videos in flight resume
 * on the next launch.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(388206553);
}

/**
 * State returns where updating stands.
 */
export function State(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1803459579);
}
