// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VideoService runs a video's lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Approve approves a gate ("" for whichever is open).
 */
export function Approve(key: string, gate: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(172943885, key, gate);
}

/**
 * Cancel stops a video.
 */
export function Cancel(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(3165389854, key);
}

/**
 * Create creates a video, and starts it when asked.
 */
export function Create($in: $models.NewVideo): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(1144714472, $in);
}

/**
 * Delete removes a video, its chapters, its tasks and the files only it uses.
 */
export function Delete(key: string): $CancellablePromise<void> {
    return $Call.ByID(3663121015, key);
}

/**
 * Get returns a video by ref (e.g. DSS-14) or id.
 */
export function Get(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(1367009544, key);
}

/**
 * List returns every video, without thumbnail designs.
 */
export function List(): $CancellablePromise<$models.VideoDTO[] | null> {
    return $Call.ByID(325413860);
}

/**
 * PushMetadata sends a published video's listing to YouTube again.
 */
export function PushMetadata(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(1999289501, key);
}

/**
 * Reject rejects a gate ("" for whichever is open).
 */
export function Reject(key: string, gate: string, reason: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(2823149223, key, gate, reason);
}

/**
 * Republish uploads a published video again as a new YouTube video.
 */
export function Republish(key: string): $CancellablePromise<$models.Republished> {
    return $Call.ByID(403781472, key);
}

/**
 * SaveMetadata replaces a video's YouTube listing. Nothing re-runs.
 */
export function SaveMetadata(key: string, m: $models.MetadataDTO): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(3751735132, key, m);
}

/**
 * Start enqueues a draft, or requeues what a stopped video stopped on.
 */
export function Start(key: string): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(2217741456, key);
}

/**
 * Update replaces a video's brief; nothing re-runs.
 */
export function Update(key: string, brief: $models.VideoBrief): $CancellablePromise<$models.VideoDTO> {
    return $Call.ByID(3711525885, key, brief);
}
